language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-18mode
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rbx-2

services:
  - redis
